"""RAG storage, indexing, and retrieval helpers."""

from .schema import (
    NAMESPACE_PROJECT_DOCS,
    NAMESPACE_SEMANTIC_MEMORY,
    SOURCE_MANUAL_FACT,
    SOURCE_MANUAL_PREFERENCE,
    SOURCE_PROJECT_DOC,
    SOURCE_SESSION_SUMMARY,
    VISIBILITY_GROUP,
    VISIBILITY_OWNER_ONLY,
    VISIBILITY_PROJECT_OWNER,
    VISIBILITY_PUBLIC,
    VISIBILITY_SUBJECT_ONLY,
    RagDocument,
    RagSearchResult,
)
from .project_docs import CURRENT_DEVELOPMENT_STATUS_SOURCE_ID
from .project_index import (
    CURRENT_STATUS_ANCHOR_MAX_CHARS,
    ProjectDocIndexStats,
    rebuild_project_doc_index,
    retrieve_current_development_status,
    retrieve_project_docs,
)
from .memory_index import MemoryRagIndexStats, rebuild_memory_rag_index, retrieve_memory
from .combined import CombinedRagResults, format_combined_rag_results, retrieve_combined_rag
from .development_report import (
    DEVELOPMENT_REPORT_EVIDENCE_MAX_CHARS,
    DEVELOPMENT_REPORT_FORMAT_RESERVE_CHARS,
    DEVELOPMENT_REPORT_MEMORY_MAX_CHARS,
    DEVELOPMENT_REPORT_PROJECT_CANDIDATE_MAX,
    DEVELOPMENT_REPORT_PROJECT_CANDIDATE_MIN,
    DEVELOPMENT_REPORT_PROJECT_CANDIDATE_MULTIPLIER,
    DEVELOPMENT_REPORT_PROJECT_MAX_CHARS,
    DEVELOPMENT_REPORT_PROJECT_MAX_PER_SOURCE,
    DEVELOPMENT_REPORT_PROJECT_RESULT_LIMIT,
    build_development_report_evidence,
    development_report_candidate_top_k,
    development_report_evidence_content_chars,
    select_development_report_project_results,
)

__all__ = [
    "NAMESPACE_PROJECT_DOCS",
    "NAMESPACE_SEMANTIC_MEMORY",
    "SOURCE_MANUAL_FACT",
    "SOURCE_MANUAL_PREFERENCE",
    "SOURCE_PROJECT_DOC",
    "SOURCE_SESSION_SUMMARY",
    "VISIBILITY_GROUP",
    "VISIBILITY_OWNER_ONLY",
    "VISIBILITY_PROJECT_OWNER",
    "VISIBILITY_PUBLIC",
    "VISIBILITY_SUBJECT_ONLY",
    "RagDocument",
    "RagSearchResult",
    "CURRENT_DEVELOPMENT_STATUS_SOURCE_ID",
    "CURRENT_STATUS_ANCHOR_MAX_CHARS",
    "ProjectDocIndexStats",
    "rebuild_project_doc_index",
    "retrieve_current_development_status",
    "retrieve_project_docs",
    "MemoryRagIndexStats",
    "rebuild_memory_rag_index",
    "retrieve_memory",
    "CombinedRagResults",
    "format_combined_rag_results",
    "retrieve_combined_rag",
    "DEVELOPMENT_REPORT_EVIDENCE_MAX_CHARS",
    "DEVELOPMENT_REPORT_FORMAT_RESERVE_CHARS",
    "DEVELOPMENT_REPORT_MEMORY_MAX_CHARS",
    "DEVELOPMENT_REPORT_PROJECT_CANDIDATE_MAX",
    "DEVELOPMENT_REPORT_PROJECT_CANDIDATE_MIN",
    "DEVELOPMENT_REPORT_PROJECT_CANDIDATE_MULTIPLIER",
    "DEVELOPMENT_REPORT_PROJECT_MAX_CHARS",
    "DEVELOPMENT_REPORT_PROJECT_MAX_PER_SOURCE",
    "DEVELOPMENT_REPORT_PROJECT_RESULT_LIMIT",
    "build_development_report_evidence",
    "development_report_candidate_top_k",
    "development_report_evidence_content_chars",
    "select_development_report_project_results",
]
